/**
 * Extension Loader - Auto-generated imports
 *
 * This file is AUTO-GENERATED by scripts/generate-extension-imports.js
 * DO NOT EDIT MANUALLY - your changes will be overwritten
 *
 * To add extensions:
 * 1. Install via the UI or manually add to /extensions/
 * 2. Run: npm run extensions:generate
 * 3. Restart the dev server
 */

import { Extension } from '@changerawr/markdown';
import { builtInExtensions, ExtensionMetadata, ExtensionWithMetadata } from './extensions';

/**
 * Extension loaders with error handling
 * Each loader wraps the import in try-catch to handle missing extensions
 */
// No installed extensions yet

/**
 * Cache for all extensions
 */
let discoveredExtensionsCache: ExtensionWithMetadata[] | null = null;
let isLoadingExtensions = false;

/**
 * Get all available extensions (built-in + optional)
 * Dynamically loads installed extensions with error handling
 */
export async function discoverExtensions(): Promise<ExtensionWithMetadata[]> {
  // Prevent concurrent loading
  if (isLoadingExtensions) {
    while (isLoadingExtensions) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    return discoveredExtensionsCache || [...builtInExtensions];
  }

  isLoadingExtensions = true;

  try {
    // Load all optional extensions with error handling
    const loadPromises = [
      
    ];

    const loadedExtensions = await Promise.all(loadPromises);
    const validExtensions = loadedExtensions.filter(ext => ext !== null);

    const all = [...builtInExtensions, ...validExtensions];

    // Log discovered extensions (only in development)
    if (process.env.NODE_ENV === 'development') {
      console.log('\n=== Markdown Extensions Loaded ===');
      all.forEach(ext => {
        console.log(
          `${ext.metadata.isBuiltIn ? '🔧' : '⚡'} ${ext.metadata.displayName} v${ext.metadata.version} ${
            ext.metadata.isBuiltIn ? '(built-in)' : '(optional)'
          }`
        );
      });
      console.log('==================================\n');
    }

    return all;
  } finally {
    isLoadingExtensions = false;
  }
}

/**
 * Get all available extensions (cached)
 * Call this to get the list of extensions for the admin UI
 */
export async function getAvailableExtensions(): Promise<ExtensionWithMetadata[]> {
  if (!discoveredExtensionsCache) {
    discoveredExtensionsCache = await discoverExtensions();
  }
  return discoveredExtensionsCache;
}

/**
 * Clear cache and re-discover extensions
 * Call this when a new extension file is added
 */
export function clearExtensionCache(): void {
  discoveredExtensionsCache = null;
}

/**
 * Get extension by name
 */
export async function getExtension(name: string): Promise<ExtensionWithMetadata | undefined> {
  const extensions = await getAvailableExtensions();
  return extensions.find(e => e.metadata.name === name);
}

/**
 * Get extensions by category
 */
export async function getExtensionsByCategory(category: string): Promise<ExtensionWithMetadata[]> {
  const extensions = await getAvailableExtensions();
  return extensions.filter(e => e.metadata.category === category);
}
