import type {Config} from "tailwindcss";

export default {
    darkMode: ["class"],
    // Safelist from @changerawr/markdown v1.2.0 — avoids module loading issues in jiti/Docker + generate tailwind from extensions
    safelist: [
        "-translate-y-1/2",
        "[&_table]:border-collapse",
        "[&_table]:my-4",
        "[&_table]:w-full",
        "[&_td]:border",
        "[&_td]:p-2",
        "[&_th]:border",
        "[&_th]:p-2",
        "absolute",
        "animate-pulse",
        "animate-spin",
        "aspect-square",
        "bg-amber-500/10",
        "bg-background",
        "bg-blue-500/10",
        "bg-blue-600",
        "bg-gradient-to-br",
        "bg-gradient-to-t",
        "bg-gray-200",
        "bg-green-500/10",
        "bg-muted",
        "bg-primary",
        "bg-red-500/10",
        "block",
        "border",
        "border-2",
        "border-amber-500/30",
        "border-b",
        "border-b-2",
        "border-blue-500/30",
        "border-border",
        "border-dashed",
        "border-green-500/30",
        "border-l-2",
        "border-l-4",
        "border-l-amber-500",
        "border-l-blue-500",
        "border-l-green-500",
        "border-l-red-500",
        "border-muted-foreground",
        "border-red-500/30",
        "border-t",
        "border-transparent",
        "bottom-0",
        "cursor-pointer",
        "dark:bg-gray-800",
        "dark:border-blue-800",
        "dark:border-gray-700",
        "dark:border-green-800",
        "dark:border-purple-800",
        "dark:border-red-800",
        "dark:border-yellow-800",
        "dark:hover:text-blue-300",
        "dark:hover:text-green-300",
        "dark:hover:text-purple-300",
        "dark:hover:text-red-300",
        "dark:hover:text-yellow-300",
        "dark:prose-invert",
        "dark:text-amber-400",
        "dark:text-blue-400",
        "dark:text-gray-100",
        "dark:text-green-400",
        "dark:text-purple-400",
        "dark:text-red-400",
        "dark:text-yellow-400",
        "disabled:cursor-not-allowed",
        "disabled:opacity-50",
        "drop-shadow-lg",
        "duration-200",
        "flex",
        "flex-1",
        "flex-col",
        "flex-shrink-0",
        "focus:outline-none",
        "focus:ring-2",
        "focus:ring-primary",
        "font-bold",
        "font-medium",
        "font-mono",
        "font-semibold",
        "from-black/60",
        "from-muted",
        "gap-1.5",
        "gap-2",
        "gap-3",
        "gap-4",
        "gd-color-tag",
        "grid",
        "grid-cols-2",
        "grid-cols-3",
        "grid-cols-4",
        "grid-cols-7",
        "group",
        "group-hover:opacity-100",
        "group-open:rotate-90",
        "h-0",
        "h-10",
        "h-12",
        "h-4",
        "h-6",
        "h-8",
        "h-[600px]",
        "h-auto",
        "h-full",
        "hover:bg-blue-700",
        "hover:bg-gray-300",
        "hover:bg-primary/90",
        "hover:opacity-100",
        "hover:ring-2",
        "hover:ring-primary",
        "hover:scale-105",
        "hover:shadow-lg",
        "hover:text-blue-700",
        "hover:text-foreground",
        "hover:text-green-700",
        "hover:text-purple-700",
        "hover:text-red-700",
        "hover:text-yellow-700",
        "hover:underline",
        "id",
        "inline-block",
        "inline-flex",
        "inset-0",
        "italic",
        "items-center",
        "justify-between",
        "justify-center",
        "leading-7",
        "leading-relaxed",
        "left-0",
        "left-3",
        "line-through",
        "list-decimal",
        "list-disc",
        "list-inside",
        "max-w-full",
        "max-w-md",
        "max-w-none",
        "mb-2",
        "mb-3",
        "mb-4",
        "mb-6",
        "min-h-0",
        "ml-4",
        "mt-1",
        "mt-2",
        "mt-3",
        "mt-4",
        "mt-5",
        "mt-6",
        "mt-8",
        "my-2",
        "my-4",
        "my-6",
        "object-cover",
        "opacity-0",
        "overflow-hidden",
        "overflow-x-auto",
        "overflow-x-hidden",
        "overflow-y-auto",
        "p-2",
        "p-3",
        "p-4",
        "p-6",
        "pl-10",
        "pl-4",
        "pl-6",
        "pr-3",
        "prose",
        "pt-1",
        "pt-3",
        "px-1",
        "px-1.5",
        "px-2",
        "px-3",
        "px-4",
        "px-6",
        "py-0.5",
        "py-1",
        "py-2",
        "py-2.5",
        "py-3",
        "py-4",
        "py-6",
        "py-8",
        "relative",
        "right-0",
        "right-2",
        "rounded",
        "rounded-full",
        "rounded-lg",
        "rounded-md",
        "select-none",
        "shadow-md",
        "shrink-0",
        "skeleton-",
        "space-y-1",
        "space-y-2",
        "space-y-4",
        "space-y-6",
        "spoiler-block",
        "spoiler-content",
        "spoiler-icon",
        "sr-only",
        "text-2xl",
        "text-3xl",
        "text-amber-600",
        "text-base",
        "text-blue-600",
        "text-center",
        "text-destructive",
        "text-gray-900",
        "text-green-600",
        "text-left",
        "text-lg",
        "text-muted-foreground",
        "text-primary",
        "text-primary-foreground",
        "text-red-600",
        "text-sm",
        "text-white",
        "text-xl",
        "text-xs",
        "to-muted/50",
        "to-transparent",
        "top-1/2",
        "top-2",
        "transition-all",
        "transition-colors",
        "transition-opacity",
        "transition-transform",
        "type",
        "underline",
        "via-transparent",
        "w-0",
        "w-4",
        "w-6",
        "w-8",
        "w-full",
        "whitespace-nowrap"
    ],
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./lib/services/core/markdown/extensions/**/*.{js,ts}",
    ],
    theme: {
        extend: {
            colors: {
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))'
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))'
                },
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))'
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))'
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))'
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))'
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))'
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))'
                }
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)'
            },
            keyframes: {
                'accordion-down': {
                    from: {
                        height: '0'
                    },
                    to: {
                        height: 'var(--radix-accordion-content-height)'
                    }
                },
                'accordion-up': {
                    from: {
                        height: 'var(--radix-accordion-content-height)'
                    },
                    to: {
                        height: '0'
                    }
                }
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out'
            }
        }
    },
    plugins: [require("tailwindcss-animate"), require('@tailwindcss/forms')],
} satisfies Config;
